### ISSUE TITLE
Feature Request - Allow Organize to rename files even if Base is not in the directory being scanned

### ISSUE THREAD

**Issue by SteveMyers75** [lubioa/switch-library-manager#1]
**Feature Request**:  Allow  **_Organize/Begin Library Organization_** to process a folder that contains just Updates and DLC and not the Base file. (Right now it says "**base file is missing**")

Most of the time new Updates and DLC are not properly named and need to be renamed before being moved into a library for use with programs like Nut. They will have names like "**10_Second_Run_Returns-Update_ver2-21**" instead of "**10 Second Run[01004D1007926800][v196608]**" 

**Switch Library Manager** is capable of fixing the name on Updates and/or DLC, but we have to move the "Base" file into the working directory before it will fix them.

**Comment by lubioa** [comment]
Most files will be included in the titles db, but if a file is not in the titles db and there is no basefile, it will be determined by the filename.

**Comment by lubioa** [comment]
[updated](https://github.com/lubioa/switch-library-manager/releases/tag/1.9.0)
